### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MikeBateman** [medhaj/fiftaghandler-cordova-plugin#1]
Hi, I have created a cordova app from scratch and i have added the plugin as shown but i get the following error when i try to build for android:

-compile:
    [javac] Compiling 4 source files to C:\Dev\hello\platforms\android\ant-build\classes
    [javac] C:\Dev\hello\platforms\android\src\com\fifty-five\fiftaghandler\cordova\FIFTagHandlerPlugin.java:8: error: ';' expected
    [javac] package com.fifty-five.fiftaghandler.cordova;
    [javac]                  ^
    [javac] 1 error

BUILD FAILED
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:720: The following error occurred while executing this line:
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:734: Compile failed; see the compiler error output for details.

Total time: 1 second

C:\Dev\hello\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f C:\Dev\hello\platforms\android\build.xml -Dout.dir=ant-build -Dgen.absolute.dir=ant-gen"
ERROR building one of the platforms: Error: C:\Dev\hello\platforms\android\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: C:\Dev\hello\platforms\android\cordova\build.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\batemanm\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

Any help would be great
Cheers
MB

**Comment by MikeBateman** [comment]
i found out that the command lines in the documentation are wrong:
'cordova plugin add com.fifty-five.fiftaghandler' This shouldn't be used as it contains the '-', 
package com.fifty-five.fiftaghandler.cordova;

I pulled down this Git Repo but this lead to another error :-(

**Comment by medhaj** [comment]
Hello Mike,

Thank you for reporting this issue. Actually, it is not related to the '-' character. The issue is related to plugin hosting binary SDK. I have made a warning comment about this in the documentation.

Cordova Registry Warning [iOS]

Installing this plugin directly from Cordova Registry results in Xcode using a broken FIFTagHandler.framework, this is because the current publish procedure to NPM breaks symlinks CB-6092. Please install the plugin through a locally cloned copy or from the plugin git repository using the following command

```
cordova plugin add https://github.com/medhaj/fiftaghandler-cordova-plugin.git
```

Please see the plugin documentation for more details.

Best regards,
Med

**Comment by MikeBateman** [comment]
Hi Med, thanks for the response i really appreciate it. I'm still having issues. If i start a new project and try to add the plug in for android only i still get build errors, here are the command i have run:

cordova create hello com.example.hello HelloWorld
cordova platform add android
cordova plugin add com.fifty-five.fiftaghandler
cordova build android

Output from the build:
-compile:
    [javac] Compiling 3 source files to C:\Dev\hello\platforms\android\ant-build\classes
    [javac] C:\Dev\hello\platforms\android\src\com\fifty-five\fiftaghandler\cordova\FIFTagHandlerPlugin.java:8: error: ';' expected
    [javac] package com.fifty-five.fiftaghandler.cordova;
    [javac]                  ^
    [javac] 1 error

The ^ is pointing to the '-' (this is why i thought it was a problem).
Am i missing something??
Cheers MB

**Comment by jonystorm** [comment]
Hi @medhaj , I'm having the same issue. I tried installing the plugin from a local copy and directly from your github and still getting the same error.

I'm on OS X Yosemite, don't know if that has anything to do with it.

Any ideas on how to solve it?

Thanks in advance.

**Comment by jonystorm** [comment]
Hi @MikeBateman , did you manage to solve that issue? How did you do it?

**Comment by MikeBateman** [comment]
I didn't solve the issue and could not find a work around, :-(

**Comment by jonystorm** [comment]
@MikeBateman  @medhaj  I found that the error is in:

project-folder/platforms/android/src/com/fiftyfive/fiftaghandler/FIFTagHandlerPlugin.java:140: error: cannot find symbol: R.raw.gtm_default_container

And this is the call: 
PendingResult<ContainerHolder> pending = tagManager.loadContainerPreferNonDefault(containerId, R.raw.gtm_default_container);

But I don't know where to check that variable definition.

**Comment by jonystorm** [comment]
I also found that gtm_default_container it's a file located in project-folder/platforms/android/res/raw but for some reason it's not getting that file info.

**Comment by jonystorm** [comment]
I think the problem it's on the gtm_default_container file. Maybe encoding, is it possible?

Everything else seems to be fine, I checked and in R.txt the resource "gtm_default_container" is defined. So I don't understand why it prompts with "cannot find symbol R.raw.gtm_default_container".

**Comment by medhaj** [comment]
Hello Guys,

I am sorry to see you having issues to install the plugin. This plugin is meant for Fifty Five clients. Yet, if you need it for your apps, here the official plugin repository https://github.com/fiftyfivemobile/fiftaghandler-cordova-plugin . It is kept up-to-date on the official repository. I first added it on my personal space since we haven't a repository for Fifty five. Now to fix the R.raw.gtm_default_container on Android, make sure to replace it with your app domain name (com.your.app.R.raw.gtm_default_container). More explanations can be found on the official repository.

Happy coding.
Med

**Comment by DeonKuhn** [comment]
I am getting the following error when trying to install the plugin - I have no idea why?

Fetching plugin "https://github.com/fiftyfivemobile/fiftaghandler-cordova-plugin" via git clone
Repository "https://github.com/fiftyfivemobile/fiftaghandler-cordova-plugin" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1435743903555/LICENSE'
    at Object.fs.renameSync (fs.js:548:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
